services:
  backend:
    build: ./pymail-api
    container_name: pymail-backend
    ports:
      - "8000:8000"
    volumes:
      - ./pymail-api:/app
    environment:
      - PYTHONPATH=/
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always

  frontend:
    build: ./pymail-webapp
    container_name: pymail-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./pymail-webapp:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always