/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Count Emails
         * @description Retorna a contagem total de emails no período especificado sem processá-los.
         */
        post: operations["count_emails_count_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Inbox */
        post: operations["analyze_inbox_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Stream
         * @description Stream NDJSON progress events then the final AnalysisResponse.
         *
         *     Each line is a JSON object terminated with a newline character:
         *       {"type":"progress","phase":"imap_fetch","fetched":N}
         *       {"type":"progress","phase":"dns_lookup","checked":K,"total":T}
         *       {"type":"done","result":{...AnalysisResponse...}}
         *       {"type":"error","status_code":N,"payload":{...}}
         */
        post: operations["analyze_stream_analyze_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Emails */
        post: operations["delete_emails_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Emails */
        post: operations["archive_emails_archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Total Emails Scanned */
            total_emails_scanned: number;
            /** Ignored Senders */
            ignored_senders: components["schemas"]["SenderStats"][];
            /** Health Score */
            health_score: number;
            /**
             * Source Grouping Mode
             * @description provider | tenant — granularity used to compute source_key
             */
            source_grouping_mode?: string | null;
        };
        /** DeleteRequest */
        DeleteRequest: {
            credentials: components["schemas"]["IMAPCredentials"];
            /** Sender Emails */
            sender_emails: string[];
        };
        /**
         * DomainReputation
         * @description Signals consulted for the sender's domain(s) (Public DNS; Optional VT).
         */
        DomainReputation: {
            /**
             * Primary Domain
             * @default
             */
            primary_domain: string;
            /** Checked Domains */
            checked_domains?: string[];
            /** Mx */
            mx?: boolean | null;
            /** Spf */
            spf?: string | null;
            /** Dmarc */
            dmarc?: string | null;
            /**
             * Dns Trust
             * @description Conservative aggregate (minimum among domain groups): -1 suspicious … +1 strong
             */
            dns_trust?: number | null;
            /** Summary Pt */
            summary_pt?: string | null;
            /** Summary En */
            summary_en?: string | null;
            /** Virustotal Malicious */
            virustotal_malicious?: number | null;
            /** Virustotal Suspicious */
            virustotal_suspicious?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description API health status
             */
            status: string;
            /**
             * Source Grouping Mode
             * @description provider | tenant — active source grouping mode
             */
            source_grouping_mode?: string | null;
        };
        /** IMAPCredentials */
        IMAPCredentials: {
            /**
             * Host
             * @description IMAP Server Host (e.g., imap.gmail.com)
             */
            host: string;
            /**
             * Email
             * Format: email
             * @description User email address
             */
            email: string;
            /**
             * Password
             * Format: password
             * @description App Password or User Password
             */
            password: string;
            /**
             * Days Limit
             * @description Number of days to look back for analysis
             */
            days_limit?: number | null;
            /**
             * Start Date
             * @description Start date for custom range (YYYY-MM-DD)
             */
            start_date?: string | null;
            /**
             * End Date
             * @description End date for custom range (YYYY-MM-DD)
             */
            end_date?: string | null;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @description API readiness status
             */
            status: string;
            /**
             * Source Grouping Mode
             * @description provider | tenant — active source grouping mode
             */
            source_grouping_mode?: string | null;
            /**
             * Virustotal Enabled
             * @description True when VIRUSTOTAL_API_KEY is set and domain reputation will include VT signals
             * @default false
             */
            virustotal_enabled: boolean;
        };
        /** SenderStats */
        SenderStats: {
            /** Sender Name */
            sender_name: string;
            /** Sender Email */
            sender_email: string;
            /** Source Key */
            source_key?: string | null;
            /** Sender Emails */
            sender_emails?: string[];
            /** Email Count */
            email_count: number;
            /** Open Rate */
            open_rate: number;
            /** Spam Score */
            spam_score: number;
            /**
             * Spam Risk
             * @description high | medium | low — estimated chance of being spam vs official sender
             */
            spam_risk?: string | null;
            domain_reputation?: components["schemas"]["DomainReputation"] | null;
            /** Unsubscribe Link */
            unsubscribe_link?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    count_emails_count_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IMAPCredentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_inbox_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IMAPCredentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_stream_analyze_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IMAPCredentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_emails_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_emails_archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
